# Generated by Django 4.2.16 on 2026-06-07 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("todo_title", models.CharField(max_length=100)),
                ("todo_description", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
